# Generated by Django 3.2.6 on 2021-08-18 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onetoone', '0004_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
